---
version: '2'
services:
  db:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    image: pedrocesarti/internet-speedtest-docker:grafana
    ports:
      - "4000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: pedrocesarti/internet-speedtest-docker:speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
